### PR TITLE
fix: race conditions

### PR DESCRIPTION
**Pull request by zaidfadhil**

### CODE REVIEW

**Review by khaledDiZ — COMMENTED** [review]
Approved 😝

**Comment by thedude61636** [comment]
giphy
Yeah stop those race conditions

**Comment by zaidfadhil** [comment]
@thedude61636 @khaledDiZ 

code contributions are welcomed. 

a

**Comment by thedude61636** [comment]
Nah I'll keep my contributions to gifs 😝

**Pull request merged**
